name: Build

on:
  push:
    branches:
      - main
      - sdist
  release:
    types:
      - published

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest hypothesis mypy rapidfuzz_capi Cython==3.0.0a10

      # The cythonized files allow installation from the sdist without cython
      - name: Generate cython
        run: |
          chmod +x ./src/jarowinkler/generate.sh
          ./src/jarowinkler/generate.sh

      - name: Build sdist
        run: |
          git apply ./tools/sdist.patch
          pip install build; python -m build --sdist
          # test whether tarball contains all files required for compiling
          pip install dist/jarowinkler-*.tar.gz

      - name: Test type stubs
        run: |
          python -m mypy.stubtest jarowinkler

      - name: Test with pytest
        run: |
          pytest tests
          python -m pytest tests

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz

  build_wheels_linux:
    needs: [build_sdist]
    name: Build wheels on ubuntu-latest/${{matrix.arch}}/${{matrix.python_tag}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [auto]
        python_tag: [ "cp36-*"]
        exclude:
          # PyPy builds not available for these platforms
          - arch: ppc64le
            python_tag: "pp37-*"
          - arch: ppc64le
            python_tag: "pp38-*"
          - arch: ppc64le
            python_tag: "pp39-*"
          - arch: s390x
            python_tag: "pp37-*"
          - arch: s390x
            python_tag: "pp38-*"
          - arch: s390x
            python_tag: "pp39-*"
    env:
      CIBW_ARCHS_LINUX: ${{matrix.arch}}
      CIBW_BUILD: ${{matrix.python_tag}}
      CIBW_TEST_SKIP: "{*_{aarch64,ppc64le,s390x},*musllinux_*}"
      CIBW_TEST_REQUIRES: pytest hypothesis
      CIBW_TEST_COMMAND: pytest {package}/tests
      CIBW_BUILD_VERBOSITY: 3

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist/*.tar.gz

      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - uses: actions/setup-python@v2

      - uses: docker/setup-qemu-action@v1
        name: Set up QEMU

      - name: Build wheel
        uses: pypa/cibuildwheel@v2.7.0
        with:
          output-dir: wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl